// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCG_AqzCxar_iaXLgxQrJSV6iF9y6qmKo',
    appId: '1:127078555029:web:e735e171b339039c7aea9c',
    messagingSenderId: '127078555029',
    projectId: 'trabalho-hamburguerias',
    authDomain: 'trabalho-hamburguerias.firebaseapp.com',
    storageBucket: 'trabalho-hamburguerias.appspot.com',
    measurementId: 'G-462CB3M8KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ1iYNdyfvZVw0IEn1wnNzbi8zGJ-DbtE',
    appId: '1:127078555029:android:0e24b3680ddffd677aea9c',
    messagingSenderId: '127078555029',
    projectId: 'trabalho-hamburguerias',
    storageBucket: 'trabalho-hamburguerias.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiGSHj1SIiONvCbkYc2S1f6SPzh-S8sEU',
    appId: '1:127078555029:ios:e6dc8c7767e0de837aea9c',
    messagingSenderId: '127078555029',
    projectId: 'trabalho-hamburguerias',
    storageBucket: 'trabalho-hamburguerias.appspot.com',
    iosBundleId: 'com.example.trabalhoHamburguerias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiGSHj1SIiONvCbkYc2S1f6SPzh-S8sEU',
    appId: '1:127078555029:ios:e6dc8c7767e0de837aea9c',
    messagingSenderId: '127078555029',
    projectId: 'trabalho-hamburguerias',
    storageBucket: 'trabalho-hamburguerias.appspot.com',
    iosBundleId: 'com.example.trabalhoHamburguerias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCG_AqzCxar_iaXLgxQrJSV6iF9y6qmKo',
    appId: '1:127078555029:web:4f56dbd033c236e27aea9c',
    messagingSenderId: '127078555029',
    projectId: 'trabalho-hamburguerias',
    authDomain: 'trabalho-hamburguerias.firebaseapp.com',
    storageBucket: 'trabalho-hamburguerias.appspot.com',
    measurementId: 'G-T9VNNXCH7B',
  );

}